<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Qlns.BusinessLogic/Qlns.BusinessLogic.csproj" />
    <ProjectReference Include="../Qlns.DataAccess/Qlns.DataAccess.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>
</Project>
