using Qlns.BusinessLogic.Modules.CoreHr.Shared;

namespace Qlns.BusinessLogic.Modules.CoreHr.Organization;

/// <summary>
/// Organizational unit (table <c>departments</c>). Hierarchy is expressed through
/// <see cref="ParentDepartmentId"/>; cycle prevention lives in <see cref="DepartmentHierarchy"/>.
/// </summary>
public sealed class Department
{
    public const int CostCenterMaxLength = 100;

    public long Id { get; }
    public string Code { get; private set; }
    public string Name { get; private set; }
    public long? ParentDepartmentId { get; private set; }
    public string? CostCenter { get; private set; }
    public string? Description { get; private set; }
    public long Version { get; private set; }
    public DateTimeOffset CreatedAt { get; }
    public DateTimeOffset UpdatedAt { get; private set; }

    public Department(
        long id,
        string code,
        string name,
        long? parentDepartmentId,
        string? costCenter,
        string? description,
        long version,
        DateTimeOffset createdAt,
        DateTimeOffset updatedAt)
    {
        if (id < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(id), "Identifier must be zero (unsaved) or positive.");
        }

        if (version <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(version), "Version must be positive.");
        }

        if (parentDepartmentId.HasValue && id > 0 && parentDepartmentId.Value == id)
        {
            throw new ArgumentException("A department cannot be its own parent.", nameof(parentDepartmentId));
        }

        Id = id;
        Code = code;
        Name = name;
        ParentDepartmentId = parentDepartmentId;
        CostCenter = costCenter;
        Description = description;
        Version = version;
        CreatedAt = createdAt;
        UpdatedAt = updatedAt;
    }

    /// <summary>New, not yet persisted department (Id 0, version 1). Call <see cref="Validate"/> first.</summary>
    public static Department Create(DepartmentWrite write, DateTimeOffset now) => new(
        0,
        write.Code,
        write.Name,
        write.ParentDepartmentId,
        write.CostCenter,
        write.Description,
        version: 1,
        createdAt: now,
        updatedAt: now);

    /// <summary>Copy carrying the identifier generated by the data layer.</summary>
    public Department WithId(long id) => new(
        id, Code, Name, ParentDepartmentId, CostCenter, Description, Version, CreatedAt, UpdatedAt);

    public bool IsRootUnit() => ParentDepartmentId is null;

    /// <summary>Replaces the editable metadata and bumps the optimistic-concurrency version.</summary>
    public void Replace(DepartmentWrite write, DateTimeOffset now)
    {
        Code = write.Code;
        Name = write.Name;
        ParentDepartmentId = write.ParentDepartmentId;
        CostCenter = write.CostCenter;
        Description = write.Description;
        Version++;
        UpdatedAt = now;
    }

    /// <summary>Validates and normalizes (trims) a write payload; throws <see cref="CoreHrValidationException"/>.</summary>
    public static DepartmentWrite Validate(DepartmentWrite write)
    {
        ArgumentNullException.ThrowIfNull(write);
        var errors = new ValidationErrors();

        var code = OrganizationCodeRules.ValidateCode(errors, write.Code);
        var name = OrganizationCodeRules.ValidateName(errors, write.Name);
        var costCenter = OrganizationCodeRules.ValidateOptional(errors, "costCenter", write.CostCenter, CostCenterMaxLength);
        var description = OrganizationCodeRules.ValidateOptional(
            errors, "description", write.Description, OrganizationCodeRules.DescriptionMaxLength);

        if (write.ParentDepartmentId is <= 0)
        {
            errors.Add("parentDepartmentId", "parentDepartmentId must be a positive identifier.");
        }

        errors.ThrowIfAny();
        return new DepartmentWrite(code, name, write.ParentDepartmentId, costCenter, description);
    }
}
