using Qlns.BusinessLogic.Modules.CoreHr.Shared;

namespace Qlns.BusinessLogic.Modules.CoreHr.Organization;

/// <summary>Position/job-title definition (table <c>positions</c>) referenced by employees and job postings.</summary>
public sealed class Position
{
    public const int LevelMaxLength = 50;

    public long Id { get; }
    public string Code { get; private set; }
    public string Name { get; private set; }
    public string? Level { get; private set; }
    public string? Description { get; private set; }
    public long Version { get; private set; }
    public DateTimeOffset CreatedAt { get; }
    public DateTimeOffset UpdatedAt { get; private set; }

    public Position(
        long id,
        string code,
        string name,
        string? level,
        string? description,
        long version,
        DateTimeOffset createdAt,
        DateTimeOffset updatedAt)
    {
        if (id < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(id), "Identifier must be zero (unsaved) or positive.");
        }

        if (version <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(version), "Version must be positive.");
        }

        Id = id;
        Code = code;
        Name = name;
        Level = level;
        Description = description;
        Version = version;
        CreatedAt = createdAt;
        UpdatedAt = updatedAt;
    }

    /// <summary>New, not yet persisted position (Id 0, version 1). Call <see cref="Validate"/> first.</summary>
    public static Position Create(PositionWrite write, DateTimeOffset now) => new(
        0, write.Code, write.Name, write.Level, write.Description, version: 1, createdAt: now, updatedAt: now);

    /// <summary>Copy carrying the identifier generated by the data layer.</summary>
    public Position WithId(long id) => new(id, Code, Name, Level, Description, Version, CreatedAt, UpdatedAt);

    /// <summary>Replaces the editable metadata and bumps the optimistic-concurrency version.</summary>
    public void Replace(PositionWrite write, DateTimeOffset now)
    {
        Code = write.Code;
        Name = write.Name;
        Level = write.Level;
        Description = write.Description;
        Version++;
        UpdatedAt = now;
    }

    /// <summary>Validates and normalizes (trims) a write payload; throws <see cref="CoreHrValidationException"/>.</summary>
    public static PositionWrite Validate(PositionWrite write)
    {
        ArgumentNullException.ThrowIfNull(write);
        var errors = new ValidationErrors();

        var code = OrganizationCodeRules.ValidateCode(errors, write.Code);
        var name = OrganizationCodeRules.ValidateName(errors, write.Name);
        var level = OrganizationCodeRules.ValidateOptional(errors, "level", write.Level, LevelMaxLength);
        var description = OrganizationCodeRules.ValidateOptional(
            errors, "description", write.Description, OrganizationCodeRules.DescriptionMaxLength);

        errors.ThrowIfAny();
        return new PositionWrite(code, name, level, description);
    }
}
