namespace Qlns.BusinessLogic.Modules.CoreHr.EmployeeEvents;

/// <summary>employee_events.event_type (ck_employee_event_type). Contract values are snake_case.</summary>
public enum EmployeeEventType
{
    ProbationConfirmation,
    ProbationExtension,
    Promotion,
    Demotion,
    Transfer,
    SalaryAdjustment,
    Suspension,
    ReturnToWork,
    Termination,
    Correction
}

public static class EmployeeEventTypeNames
{
    /// <summary>
    /// Types a client may create through <c>POST /employees/{id}/events</c> (EmployeeEventWrite.eventType).
    /// The remaining types are generated by probation review, suspension handling and offboarding.
    /// </summary>
    public static readonly IReadOnlySet<EmployeeEventType> ClientWritable = new HashSet<EmployeeEventType>
    {
        EmployeeEventType.Promotion,
        EmployeeEventType.Transfer,
        EmployeeEventType.Demotion,
        EmployeeEventType.SalaryAdjustment,
        EmployeeEventType.Termination,
        EmployeeEventType.Correction
    };

    public static string ToContract(this EmployeeEventType type) => type switch
    {
        EmployeeEventType.ProbationConfirmation => "probation_confirmation",
        EmployeeEventType.ProbationExtension => "probation_extension",
        EmployeeEventType.Promotion => "promotion",
        EmployeeEventType.Demotion => "demotion",
        EmployeeEventType.Transfer => "transfer",
        EmployeeEventType.SalaryAdjustment => "salary_adjustment",
        EmployeeEventType.Suspension => "suspension",
        EmployeeEventType.ReturnToWork => "return_to_work",
        EmployeeEventType.Termination => "termination",
        EmployeeEventType.Correction => "correction",
        _ => throw new ArgumentOutOfRangeException(nameof(type))
    };

    public static bool TryParseContract(string? value, out EmployeeEventType type)
    {
        type = value switch
        {
            "probation_confirmation" => EmployeeEventType.ProbationConfirmation,
            "probation_extension" => EmployeeEventType.ProbationExtension,
            "promotion" => EmployeeEventType.Promotion,
            "demotion" => EmployeeEventType.Demotion,
            "transfer" => EmployeeEventType.Transfer,
            "salary_adjustment" => EmployeeEventType.SalaryAdjustment,
            "suspension" => EmployeeEventType.Suspension,
            "return_to_work" => EmployeeEventType.ReturnToWork,
            "termination" => EmployeeEventType.Termination,
            "correction" => EmployeeEventType.Correction,
            _ => default
        };

        return value is "probation_confirmation" or "probation_extension" or "promotion" or "demotion" or
            "transfer" or "salary_adjustment" or "suspension" or "return_to_work" or "termination" or "correction";
    }
}
